# Mobuntu Orange — RC1-mkosi
# Profile: plasma-mobile
# Activated with: mkosi --profile plasma-mobile build

[Content]
Packages=
    plasma-mobile
    maliit-keyboard
    sddm

PostInstallationScripts=mkosi.profiles/plasma-mobile/mkosi.postinst.plasma
