#!/bin/bash
# Mobuntu — RC14
set -e
source build.env
echo "======================================================="
echo "   Mobuntu — [5/5] Seal & Flash ($DEVICE_NAME)"
echo "======================================================="

BOOT_IMG=""
KERNEL_LZ4=""
INITRD_LZ4=""
DTB_OUT=""
ROOT_IMG="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_root.img"
ROOT_SPARSE="${ROOT_IMG%.img}_sparse.img"

# Clean any leftover mounts
for d in run sys proc dev/pts dev; do
    if mountpoint -q "$ROOTFS_DIR/$d"; then
        sudo umount -l "$ROOTFS_DIR/$d"
    fi
done

# -------------------------------------------------------
# Step 1: UUID
# -------------------------------------------------------
BUILD_UUID=$(uuidgen)
echo ">>> UUID: $BUILD_UUID"
sed -i '/^ROOTFS_UUID=/d' build.env 2>/dev/null || true
echo "ROOTFS_UUID=$BUILD_UUID" >> build.env

# -------------------------------------------------------
# Step 2: DTB selection
# -------------------------------------------------------
if [ "$BOOT_PANEL_PICKER" = "true" ]; then
    echo ""
    echo "Select display panel:"
    echo "1) Tianma (default)"
    echo "2) EBBG"
    read -p "Choice [1-2, default 1]: " PANEL_CHOICE
    case ${PANEL_CHOICE:-1} in
        2) SELECTED_DTB="sdm845-xiaomi-beryllium-ebbg.dtb"  ;;
        *) SELECTED_DTB="sdm845-xiaomi-beryllium-tianma.dtb" ;;
    esac
else
    SELECTED_DTB="${BOOT_DTB_SELECTED:-$BOOT_DTB}"
fi
echo ">>> DTB: $SELECTED_DTB"

if [ "$BOOT_METHOD" = "mkbootimg" ]; then
    sudo bash -c "echo '${SELECTED_DTB}' > '${ROOTFS_DIR}/etc/kernel/boot_dtb'"
fi

# -------------------------------------------------------
# Step 3: Boot verbosity + autoresize
# -------------------------------------------------------
echo ""
echo "Boot verbosity:"
echo "1) Quiet / splash (default)"
echo "2) Verbose"
read -p "Choice [1-2, default 1]: " BOOT_V
case ${BOOT_V:-1} in
    2) BOOT_EXTRA="" ;;
    *) BOOT_EXTRA="quiet splash" ;;
esac

echo ""
echo "Auto-resize rootfs to fill partition on first boot?"
echo "1) Yes (recommended)"
echo "2) No"
read -p "Choice [1-2, default 1]: " RESIZE_CHOICE
AUTORESIZE=${RESIZE_CHOICE:-1}

# -------------------------------------------------------
# Step 4: Write /etc/kernel/cmdline + fstab
# -------------------------------------------------------
#CMDLINE="root=UUID=${BUILD_UUID} rw rootwait console=tty0 console=ttyMSM0,115200n8 earlycon=qcom_geni,0x00A90000 ${BOOT_EXTRA}"

# This cmdline works best in my opinion ;)
CMDLINE="root=UUID=${BUILD_UUID} earlycon console=tty0 console=ttyMSM0,115200 init=/sbin/init ro loglevel=7"

echo ">>> Writing /etc/kernel/cmdline..."
sudo bash -c "echo '${CMDLINE}' > '${ROOTFS_DIR}/etc/kernel/cmdline'"

echo ">>> Writing fstab..."
sudo bash -c "printf '# Mobuntu — generated by 5_seal_rootfs.sh\nUUID=${BUILD_UUID}  /  ext4  errors=remount-ro  0  1\n' > '${ROOTFS_DIR}/etc/fstab'"

# -------------------------------------------------------
# Autoresize first-boot service
# -------------------------------------------------------
if [ "${AUTORESIZE:-1}" = "1" ]; then
    echo ">>> Installing first-boot autoresize service..."
    sudo bash -c "cat > '${ROOTFS_DIR}/etc/systemd/system/mobuntu-resize.service'" << 'RESIZEOF'
[Unit]
Description=Mobuntu — Resize rootfs to fill partition (first boot)
After=local-fs.target
ConditionPathExists=/etc/mobuntu-resize-pending

[Service]
Type=oneshot
ExecStart=/usr/sbin/resize2fs /dev/disk/by-label/${DEVICE_IMAGE_LABEL}
ExecStartPost=/bin/rm -f /etc/mobuntu-resize-pending
ExecStartPost=/sbin/reboot
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
RESIZEOF
    sudo bash -c "ln -sf /etc/systemd/system/mobuntu-resize.service \
        '${ROOTFS_DIR}/etc/systemd/system/multi-user.target.wants/mobuntu-resize.service'"
    sudo touch "${ROOTFS_DIR}/etc/mobuntu-resize-pending"
    echo ">>> Autoresize service installed."
fi

# -------------------------------------------------------
# Step 5: Boot image — method-specific
# -------------------------------------------------------
case "$BOOT_METHOD" in
mkbootimg)
    echo ">>> Regenerating initramfs with firmware in place..."
    sudo chroot "$ROOTFS_DIR" update-initramfs -u -k all

    echo ">>> Verifying firmware blobs inside initrd (warn only)..."
    INITRD_CHECK=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img-*sdm845* 2>/dev/null | tail -n 1)
    if [ -n "$INITRD_CHECK" ]; then
        INITRD_CONTENTS=$(lsinitramfs "$INITRD_CHECK" 2>/dev/null || true)
        for blob in "usr/lib/firmware/qcom/a630_sqe.fw" \
                    "usr/lib/firmware/qcom/a630_gmu.bin" \
                    "usr/lib/firmware/qcom/sdm845/beryllium/adsp.mbn" \
                    "usr/lib/firmware/qcom/sdm845/beryllium/cdsp.mbn"; do
            if echo "$INITRD_CONTENTS" | grep -q "$blob"; then
                echo "  [OK]   $blob"
            else
                echo "  [WARN] $blob — NOT found in initrd (non-fatal)"
            fi
        done
        echo ">>> Initrd size: $(du -h $INITRD_CHECK | cut -f1)"
    else
        echo ">>> WARNING: Could not locate initrd for verification — proceeding."
    fi

    echo ">>> Finding boot assets..."
    KERNEL=$(ls -1tr "$ROOTFS_DIR"/boot/vmlinuz-*sdm845* 2>/dev/null | tail -n 1)
    INITRD=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img-*sdm845* 2>/dev/null | tail -n 1)
    DTB=$(find "$ROOTFS_DIR/usr/lib" "$ROOTFS_DIR/boot" \
        -type f -name "$SELECTED_DTB" 2>/dev/null | head -n 1)

    if [[ -z "$KERNEL" || -z "$INITRD" || -z "$DTB" ]]; then
        echo "ERROR: Missing boot assets."
        echo "  Kernel: ${KERNEL:-NOT FOUND}"
        echo "  Initrd: ${INITRD:-NOT FOUND}"
        echo "  DTB:    ${DTB:-NOT FOUND}"
        ls -la "$ROOTFS_DIR/boot/" 2>/dev/null || true
        exit 1
    fi

    echo ">>> Kernel: $(basename $KERNEL)"
    echo ">>> Initrd: $(basename $INITRD)"
    echo ">>> DTB:    $(basename $DTB)"

    BOOT_IMG="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_boot.img"

    if [ "$BOOT_DTB_APPEND" = "true" ]; then
        echo ">>> Appending DTB to kernel (required for this device)..."
        KERNEL_DTB=$(mktemp /tmp/kernel-dtb-XXXX)
        cat "$KERNEL" "$DTB" > "$KERNEL_DTB"
    else
        KERNEL_DTB="$KERNEL"
    fi

    echo ">>> Building boot.img..."
    mkbootimg \
        --kernel "$KERNEL_DTB" \
        --ramdisk "$INITRD" \
        --pagesize "$MKBOOTIMG_PAGESIZE" \
        --base "$MKBOOTIMG_BASE" \
        --kernel_offset "$MKBOOTIMG_KERNEL_OFFSET" \
        --ramdisk_offset "$MKBOOTIMG_RAMDISK_OFFSET" \
        --tags_offset "$MKBOOTIMG_TAGS_OFFSET" \
        --cmdline "$CMDLINE" \
        -o "$BOOT_IMG"

    [ "$BOOT_DTB_APPEND" = "true" ] && rm -f "$KERNEL_DTB"
    echo ">>> boot.img: $(du -h $BOOT_IMG | cut -f1)"
    ;;

l4t)
    echo ">>> L4T bootfiles mode — preparing kernel, initrd, DTB..."

    if ! command -v lz4 &>/dev/null; then
        echo "ERROR: lz4 not found on host. Install with: sudo apt install lz4"
        exit 1
    fi

    KERNEL=$(ls -1tr "$ROOTFS_DIR"/boot/vmlinuz-* 2>/dev/null | tail -n 1)
    INITRD=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img-* 2>/dev/null | tail -n 1)
    DTB=$(find "$ROOTFS_DIR/usr/lib" "$ROOTFS_DIR/boot" \
        -type f -name "$SELECTED_DTB" 2>/dev/null | head -n 1)

    if [[ -z "$KERNEL" || -z "$INITRD" || -z "$DTB" ]]; then
        echo "ERROR: Missing boot assets."
        echo "  Kernel: ${KERNEL:-NOT FOUND}"
        echo "  Initrd: ${INITRD:-NOT FOUND}"
        echo "  DTB:    ${DTB:-NOT FOUND}"
        ls -la "$ROOTFS_DIR/boot/" 2>/dev/null || true
        exit 1
    fi

    echo ">>> Kernel: $(basename $KERNEL)"
    echo ">>> Initrd: $(basename $INITRD)"
    echo ">>> DTB:    $(basename $DTB)"

    KERNEL_LZ4="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_kernel.lz4"
    INITRD_LZ4="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_initrd.lz4"
    DTB_OUT="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_${SELECTED_DTB}"

    echo ">>> Compressing kernel with lz4..."
    lz4 -B6 --content-size -f "$KERNEL" "$KERNEL_LZ4"

    echo ">>> Compressing initrd with lz4..."
    lz4 -B6 --content-size -f "$INITRD" "$INITRD_LZ4"

    echo ">>> Copying DTB..."
    cp "$DTB" "$DTB_OUT"

    echo ">>> L4T boot files:"
    echo "    Kernel: $(du -h $KERNEL_LZ4 | cut -f1)  $KERNEL_LZ4"
    echo "    Initrd: $(du -h $INITRD_LZ4 | cut -f1)  $INITRD_LZ4"
    echo "    DTB:    $(du -h $DTB_OUT | cut -f1)  $DTB_OUT"
    ;;

uboot)
    echo ">>> U-Boot method: placeholder."
    echo ">>> UBOOT_URL=${UBOOT_URL}"
    ;;

uefi)
    echo ">>> UEFI method: placeholder."
    echo ">>> UEFI_URL=${UEFI_URL}"
    ;;

*)
    echo ">>> ERROR: Unknown BOOT_METHOD '$BOOT_METHOD'"
    exit 1
    ;;
esac

# -------------------------------------------------------
# Step 6: RootFS image
# -------------------------------------------------------
IMG_MB=$((IMAGE_SIZE * 1024))
echo ">>> Allocating ${IMAGE_SIZE}GB rootfs image..."
rm -f "$ROOT_IMG"
fallocate -l "${IMG_MB}M" "$ROOT_IMG"
mkfs.ext4 -U "$BUILD_UUID" -L "$DEVICE_IMAGE_LABEL" "$ROOT_IMG"

echo ">>> Rsyncing rootfs (this will take a while)..."
LOOP_MNT=$(mktemp -d /tmp/rootfs_mnt_XXXX)
sudo mount -o loop "$ROOT_IMG" "$LOOP_MNT"
sudo rsync -aHAXx \
    --exclude='/proc/*' --exclude='/sys/*' \
    --exclude='/dev/*'  --exclude='/run/*' \
    --exclude='/tmp/*' \
    "$ROOTFS_DIR/" "$LOOP_MNT/"
sudo sync
sudo umount "$LOOP_MNT"
rmdir "$LOOP_MNT"
echo ">>> RootFS: $(du -h $ROOT_IMG | cut -f1)"

# -------------------------------------------------------
# Step 7: Sparse conversion
# -------------------------------------------------------
if command -v img2simg &>/dev/null; then
    echo ">>> Converting to sparse..."
    img2simg "$ROOT_IMG" "$ROOT_SPARSE"
    FLASH_ROOT="$ROOT_SPARSE"
else
    echo ">>> img2simg not found, using raw image."
    FLASH_ROOT="$ROOT_IMG"
fi

# -------------------------------------------------------
# Flash instructions
# -------------------------------------------------------
echo ""
echo "======================================================="
echo "   DONE — $DEVICE_NAME"
echo "======================================================="
echo ""

case "$BOOT_METHOD" in
l4t)
    echo "  Copy boot files to SD card (/switchroot/ubuntu/):"
    echo "    $(pwd)/$KERNEL_LZ4  ->  switchroot/ubuntu/kernel.lz4"
    echo "    $(pwd)/$INITRD_LZ4  ->  switchroot/ubuntu/initrd.lz4"
    echo "    $(pwd)/$DTB_OUT     ->  switchroot/ubuntu/$SELECTED_DTB"
    echo ""
    echo "  Flash rootfs to Linux partition:"
    echo "    Use Hekate -> Tools -> USB Tools to mount SD card, then:"
    echo "    dd if=$(pwd)/$FLASH_ROOT of=/dev/{linux-partition} bs=4M status=progress"
    echo "    Or use Hekate -> Flash Linux (place rootfs in switchroot/install/)"
    ;;
*)
    if [ -n "$BOOT_IMG" ]; then
        echo "  fastboot flash boot   $(pwd)/$BOOT_IMG"
    fi
    echo "  fastboot flash system $(pwd)/$FLASH_ROOT"
    echo "  fastboot reboot"
    ;;
esac

echo ""
case "$FIRMWARE_METHOD" in
git)
    echo "  Firmware was pre-staged from:"
    echo "  $FIRMWARE_REPO"
    echo "  No first-boot firmware step required."
    ;;
apt)
    echo "  Firmware: shipped via linux-firmware apt package."
    ;;
esac
echo "======================================================="
