#!/bin/bash
# Mobuntu — RC15
set -e

# Always resolve the repo root from the script's own location —
# never rely on build.env for SCRIPT_DIR since it may be stale or empty.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "${SCRIPT_DIR}/build.env"
echo "======================================================="
echo "   Mobuntu — [5/5] Seal & Flash ($DEVICE_NAME)"
echo "======================================================="

BOOT_IMG=""
KERNEL_LZ4=""
INITRD_LZ4=""
DTB_OUT=""
ROOT_IMG="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_root.img"
ROOT_SPARSE="${ROOT_IMG%.img}_sparse.img"
DEVICE_TARBALL="${DEVICE_IMAGE_LABEL}-${UBUNTU_RELEASE}.tar.gz"

# -------------------------------------------------------
# Step 0: Unpack device tarball from debos
# -------------------------------------------------------
if [ ! -f "$DEVICE_TARBALL" ]; then
    echo "ERROR: Device tarball not found: $DEVICE_TARBALL"
    echo "       Run run_build.sh first."
    exit 1
fi

ROOTFS_DIR="mobuntu-${DEVICE_CODENAME}-${UBUNTU_RELEASE}-seal"
echo ">>> Unpacking device tarball: $DEVICE_TARBALL"
rm -rf "$ROOTFS_DIR"
mkdir -p "$ROOTFS_DIR"
sudo tar -xzf "$DEVICE_TARBALL" -C "$ROOTFS_DIR/"
echo ">>> Unpacked to: $ROOTFS_DIR"

# -------------------------------------------------------
# Step 1: UUID
# -------------------------------------------------------
BUILD_UUID=$(uuidgen)
echo ">>> UUID: $BUILD_UUID"
sed -i '/^ROOTFS_UUID=/d' build.env 2>/dev/null || true
echo "ROOTFS_UUID=$BUILD_UUID" >> build.env

# -------------------------------------------------------
# Step 2: DTB selection
# -------------------------------------------------------
if [ "$BOOT_PANEL_PICKER" = "true" ]; then
    echo ""
    echo "Select display panel:"
    echo "1) Tianma (default)"
    echo "2) EBBG"
    read -p "Choice [1-2, default 1]: " PANEL_CHOICE
    case ${PANEL_CHOICE:-1} in
        2) SELECTED_DTB="sdm845-xiaomi-beryllium-ebbg.dtb"  ;;
        *) SELECTED_DTB="sdm845-xiaomi-beryllium-tianma.dtb" ;;
    esac
else
    SELECTED_DTB="${BOOT_DTB_SELECTED:-$BOOT_DTB}"
fi
echo ">>> DTB: $SELECTED_DTB"

if [ "$BOOT_METHOD" = "mkbootimg" ]; then
    sudo bash -c "echo '${SELECTED_DTB}' > '${ROOTFS_DIR}/etc/kernel/boot_dtb'"
fi

# -------------------------------------------------------
# Step 3: Boot verbosity + autoresize
# -------------------------------------------------------
echo ""
echo "Auto-resize rootfs on first boot?"
echo "1) Yes (recommended)"
echo "2) No"
read -p "Choice [1-2, default 1]: " RESIZE_CHOICE
AUTORESIZE=${RESIZE_CHOICE:-1}

# -------------------------------------------------------
# Step 4: Write /etc/kernel/cmdline + fstab
# -------------------------------------------------------
CMDLINE="root=UUID=${BUILD_UUID} earlycon console=tty0 console=ttyMSM0,115200 init=/sbin/init ro loglevel=7"

echo ">>> Writing /etc/kernel/cmdline..."
sudo bash -c "echo '${CMDLINE}' > '${ROOTFS_DIR}/etc/kernel/cmdline'"

echo ">>> Writing fstab..."
sudo bash -c "printf '# Mobuntu RC15 — generated by 5_seal_rootfs.sh\nUUID=${BUILD_UUID}  /  ext4  errors=remount-ro  0  1\n' > '${ROOTFS_DIR}/etc/fstab'"

# -------------------------------------------------------
# Autoresize first-boot service
# -------------------------------------------------------
if [ "${AUTORESIZE:-1}" = "1" ]; then
    echo ">>> Installing autoresize service..."
    sudo bash -c "cat > '${ROOTFS_DIR}/etc/systemd/system/mobuntu-resize.service'" << 'RESIZEOF'
[Unit]
Description=Mobuntu — Resize rootfs to fill partition (first boot)
After=local-fs.target
ConditionPathExists=/etc/mobuntu-resize-pending

[Service]
Type=oneshot
ExecStart=/usr/sbin/resize2fs /dev/disk/by-label/${DEVICE_IMAGE_LABEL}
ExecStartPost=/bin/rm -f /etc/mobuntu-resize-pending
ExecStartPost=/sbin/reboot
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
RESIZEOF
    sudo bash -c "ln -sf /etc/systemd/system/mobuntu-resize.service \
        '${ROOTFS_DIR}/etc/systemd/system/multi-user.target.wants/mobuntu-resize.service'"
    sudo touch "${ROOTFS_DIR}/etc/mobuntu-resize-pending"
fi

# -------------------------------------------------------
# Step 5: Boot image — method-specific
# -------------------------------------------------------
case "$BOOT_METHOD" in
mkbootimg)
    # Stage firmware blobs into rootfs BEFORE update-initramfs runs so
    # initramfs-tools firmware hook picks them up naturally.
    echo ">>> Staging firmware into rootfs before initramfs generation..."
    FW_BUNDLE="${SCRIPT_DIR}/firmware/${DEVICE_BRAND}-${DEVICE_CODENAME}/firmware.tar.gz"
    if [ -f "$FW_BUNDLE" ]; then
        sudo tar -xzf "$FW_BUNDLE" -C "$ROOTFS_DIR/" 2>/dev/null || true
        echo "    Staged: firmware bundle ($(du -sh $FW_BUNDLE | cut -f1))"
    else
        echo "    [WARN] No firmware bundle at $FW_BUNDLE"
    fi

    # Ensure GPU firmware is present — fetch from kernel.org if missing
    for blob in a630_sqe.fw a630_gmu.bin; do
        if [ ! -f "$ROOTFS_DIR/lib/firmware/qcom/$blob" ]; then
            echo "    Fetching $blob from kernel.org..."
            sudo mkdir -p "$ROOTFS_DIR/lib/firmware/qcom"
            sudo curl -fsSL -o "$ROOTFS_DIR/lib/firmware/qcom/$blob"                 "https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/qcom/$blob"                 2>/dev/null && echo "    OK: $blob" || echo "    [WARN] Failed to fetch $blob"
        fi
    done

    echo ">>> Injecting firmware into initramfs..."
    # Inject firmware directly into the existing initrd via cpio on the host.
    # This avoids running update-initramfs inside a chroot which requires
    # qemu-aarch64-static + working binfmt_misc — both unreliable in WSL2.

    # Resolve to absolute path BEFORE any cd — relative paths break
    # the moment we cd into the temp injection directory.
    ROOTFS_DIR="$(realpath "$ROOTFS_DIR")"

    INITRD_FILE=$(ls -1 "$ROOTFS_DIR/boot/initrd.img-"*sdm845* 2>/dev/null | head -1)
    if [ -z "$INITRD_FILE" ]; then
        echo "    [WARN] No sdm845 initrd found — skipping firmware injection"
    else
        INJECT_TMP=$(mktemp -d /tmp/initrd-inject-XXXX)
        echo "    Unpacking $(basename $INITRD_FILE) ($(du -sh $INITRD_FILE | cut -f1))..."
        cd "$INJECT_TMP"

        INITRD_FORMAT=$(file "$INITRD_FILE")
        if echo "$INITRD_FORMAT" | grep -q "gzip"; then
            zcat "$INITRD_FILE" | sudo cpio -id --quiet 2>/dev/null || true
            COMPRESS="gzip"
        elif echo "$INITRD_FORMAT" | grep -q "LZ4"; then
            lz4 -d "$INITRD_FILE" - 2>/dev/null | sudo cpio -id --quiet 2>/dev/null || true
            COMPRESS="lz4"
        elif echo "$INITRD_FORMAT" | grep -q "Zstandard"; then
            zstd -d "$INITRD_FILE" -c 2>/dev/null | sudo cpio -id --quiet 2>/dev/null || true
            COMPRESS="zstd"
        else
            # Raw uncompressed cpio
            sudo cpio -id --quiet < "$INITRD_FILE" 2>/dev/null || true
            COMPRESS="none"
        fi
        echo "    Format: $COMPRESS"

        echo "    Injecting firmware blobs..."
        for fw_src in \
            "$ROOTFS_DIR/lib/firmware/qcom" \
            "$ROOTFS_DIR/usr/lib/firmware/qcom"; do
            [ -d "$fw_src" ] || continue
            sudo mkdir -p "${INJECT_TMP}/usr/lib/firmware/qcom"
            sudo cp -rn "$fw_src/." "${INJECT_TMP}/usr/lib/firmware/qcom/" 2>/dev/null || true
        done

        FW_COUNT=$(find "$INJECT_TMP/usr/lib/firmware" -type f 2>/dev/null | wc -l)
        echo "    Firmware files in initrd: $FW_COUNT"

        echo "    Repacking initrd ($COMPRESS)..."
        case "$COMPRESS" in
            gzip) sudo find . | sudo cpio -o -H newc --quiet 2>/dev/null | \
                    gzip -9 | sudo tee "$INITRD_FILE" > /dev/null ;;
            lz4)  sudo find . | sudo cpio -o -H newc --quiet 2>/dev/null | \
                    lz4 -9 | sudo tee "$INITRD_FILE" > /dev/null ;;
            zstd) sudo find . | sudo cpio -o -H newc --quiet 2>/dev/null | \
                    zstd -19 | sudo tee "$INITRD_FILE" > /dev/null ;;
            *)    sudo find . | sudo cpio -o -H newc --quiet 2>/dev/null | \
                    sudo tee "$INITRD_FILE" > /dev/null ;;
        esac

        cd - > /dev/null
        sudo rm -rf "$INJECT_TMP"
        echo "    Done: $(du -sh $INITRD_FILE | cut -f1)"
    fi

    echo ">>> Verifying firmware blobs inside initrd (warn only)..."
    INITRD_CHECK=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img-*sdm845* 2>/dev/null | tail -n 1)
    if [ -n "$INITRD_CHECK" ]; then
        INITRD_CONTENTS=$(lsinitramfs "$INITRD_CHECK" 2>/dev/null || true)
        for blob in "usr/lib/firmware/qcom/a630_sqe.fw" \
                    "usr/lib/firmware/qcom/a630_gmu.bin" \
                    "usr/lib/firmware/qcom/sdm845/beryllium/adsp.mbn" \
                    "usr/lib/firmware/qcom/sdm845/beryllium/cdsp.mbn"; do
            echo "$INITRD_CONTENTS" | grep -q "$blob" && \
                echo "  [OK]   $blob" || \
                echo "  [WARN] $blob — NOT in initrd (non-fatal)"
        done
        echo ">>> Initrd: $(du -h $INITRD_CHECK | cut -f1)"
    fi

    echo ">>> Finding boot assets..."
    KERNEL=$(ls -1tr "$ROOTFS_DIR"/boot/vmlinuz-*sdm845* 2>/dev/null | tail -n 1)
    INITRD=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img-*sdm845* 2>/dev/null | tail -n 1)
    DTB=$(find "$ROOTFS_DIR/usr/lib" "$ROOTFS_DIR/boot" \
        -type f -name "$SELECTED_DTB" 2>/dev/null | head -n 1)

    if [[ -z "$KERNEL" || -z "$INITRD" || -z "$DTB" ]]; then
        echo "ERROR: Missing boot assets."
        echo "  Kernel: ${KERNEL:-NOT FOUND}"
        echo "  Initrd: ${INITRD:-NOT FOUND}"
        echo "  DTB:    ${DTB:-NOT FOUND}"
        exit 1
    fi

    echo ">>> Kernel: $(basename $KERNEL)"
    echo ">>> Initrd: $(basename $INITRD)"
    echo ">>> DTB:    $(basename $DTB)"

    BOOT_IMG="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_boot.img"

    if [ "$BOOT_DTB_APPEND" = "true" ]; then
        KERNEL_DTB=$(mktemp /tmp/kernel-dtb-XXXX)
        cat "$KERNEL" "$DTB" > "$KERNEL_DTB"
    else
        KERNEL_DTB="$KERNEL"
    fi

    mkbootimg \
        --kernel "$KERNEL_DTB" \
        --ramdisk "$INITRD" \
        --pagesize "$MKBOOTIMG_PAGESIZE" \
        --base "$MKBOOTIMG_BASE" \
        --kernel_offset "$MKBOOTIMG_KERNEL_OFFSET" \
        --ramdisk_offset "$MKBOOTIMG_RAMDISK_OFFSET" \
        --tags_offset "$MKBOOTIMG_TAGS_OFFSET" \
        --cmdline "$CMDLINE" \
        -o "$BOOT_IMG"

    [ "$BOOT_DTB_APPEND" = "true" ] && rm -f "$KERNEL_DTB"
    echo ">>> boot.img: $(du -h $BOOT_IMG | cut -f1)"
    ;;

l4t)
    echo ">>> L4T bootfiles mode..."
    command -v lz4 &>/dev/null || { echo "ERROR: lz4 not installed"; exit 1; }

    KERNEL=$(ls -1tr "$ROOTFS_DIR"/boot/vmlinuz-* 2>/dev/null | tail -n 1)
    INITRD=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img-* 2>/dev/null | tail -n 1)
    DTB=$(find "$ROOTFS_DIR/usr/lib" "$ROOTFS_DIR/boot" \
        -type f -name "$SELECTED_DTB" 2>/dev/null | head -n 1)

    if [[ -z "$KERNEL" || -z "$INITRD" || -z "$DTB" ]]; then
        echo "ERROR: Missing boot assets."
        echo "  Kernel: ${KERNEL:-NOT FOUND}"
        echo "  Initrd: ${INITRD:-NOT FOUND}"
        echo "  DTB:    ${DTB:-NOT FOUND}"
        exit 1
    fi

    KERNEL_LZ4="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_kernel.lz4"
    INITRD_LZ4="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_initrd.lz4"
    DTB_OUT="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_${SELECTED_DTB}"

    lz4 -B6 --content-size -f "$KERNEL" "$KERNEL_LZ4"
    lz4 -B6 --content-size -f "$INITRD" "$INITRD_LZ4"
    cp "$DTB" "$DTB_OUT"

    echo ">>> Kernel: $(du -h $KERNEL_LZ4 | cut -f1)  $KERNEL_LZ4"
    echo ">>> Initrd: $(du -h $INITRD_LZ4 | cut -f1)  $INITRD_LZ4"
    echo ">>> DTB:    $(du -h $DTB_OUT | cut -f1)  $DTB_OUT"
    ;;

uboot) echo ">>> U-Boot: placeholder (UBOOT_URL=${UBOOT_URL})" ;;
uefi)  echo ">>> UEFI: placeholder (UEFI_URL=${UEFI_URL})"     ;;
*)     echo "ERROR: Unknown BOOT_METHOD '$BOOT_METHOD'"; exit 1 ;;
esac

# -------------------------------------------------------
# Step 6: RootFS image
# -------------------------------------------------------
IMG_MB=$((IMAGE_SIZE * 1024))
echo ">>> Allocating ${IMAGE_SIZE}GB rootfs image..."
rm -f "$ROOT_IMG"
fallocate -l "${IMG_MB}M" "$ROOT_IMG"
mkfs.ext4 -U "$BUILD_UUID" -L "$DEVICE_IMAGE_LABEL" "$ROOT_IMG"

echo ">>> Rsyncing rootfs..."
LOOP_MNT=$(mktemp -d /tmp/rootfs_mnt_XXXX)
sudo mount -o loop "$ROOT_IMG" "$LOOP_MNT"
sudo rsync -aHAXx \
    --exclude='/proc/*' --exclude='/sys/*' \
    --exclude='/dev/*'  --exclude='/run/*' \
    --exclude='/tmp/*' \
    "$ROOTFS_DIR/" "$LOOP_MNT/"
sudo sync
sudo umount "$LOOP_MNT"
rmdir "$LOOP_MNT"
echo ">>> RootFS: $(du -h $ROOT_IMG | cut -f1)"

# -------------------------------------------------------
# Step 7: Sparse conversion
# -------------------------------------------------------
if command -v img2simg &>/dev/null; then
    img2simg "$ROOT_IMG" "$ROOT_SPARSE"
    FLASH_ROOT="$ROOT_SPARSE"
else
    echo ">>> img2simg not found, using raw image."
    FLASH_ROOT="$ROOT_IMG"
fi

# -------------------------------------------------------
# Cleanup unpacked rootfs
# -------------------------------------------------------
echo ">>> Cleaning up unpacked rootfs..."
sudo rm -rf "$ROOTFS_DIR"

# -------------------------------------------------------
# Flash instructions
# -------------------------------------------------------
echo ""
echo "======================================================="
echo "   DONE — $DEVICE_NAME"
echo "======================================================="
echo ""
case "$BOOT_METHOD" in
l4t)
    echo "  Copy boot files to SD card (/switchroot/ubuntu/):"
    echo "    $KERNEL_LZ4  ->  switchroot/ubuntu/kernel.lz4"
    echo "    $INITRD_LZ4  ->  switchroot/ubuntu/initrd.lz4"
    echo "    $DTB_OUT     ->  switchroot/ubuntu/$SELECTED_DTB"
    echo ""
    echo "  Flash rootfs to Linux partition via Hekate UMS or:"
    echo "    dd if=$FLASH_ROOT of=/dev/{linux-partition} bs=4M status=progress"
    ;;
*)
    [ -n "$BOOT_IMG" ] && echo "  fastboot flash boot   $(pwd)/$BOOT_IMG"
    echo "  fastboot flash system $(pwd)/$FLASH_ROOT"
    echo "  fastboot reboot"
    ;;
esac
echo ""
case "$FIRMWARE_METHOD" in
git) echo "  Firmware pre-staged from: $FIRMWARE_REPO" ;;
apt) echo "  Firmware: linux-firmware apt package."     ;;
esac
echo "======================================================="
