#!/bin/bash
set -e
source build.env
echo "======================================================="
echo "   Mobuntu Orange — [5/5] Seal & Flash ($DEVICE_NAME)"
echo "======================================================="

BOOT_IMG="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_boot.img"
ROOT_IMG="${DEVICE_IMAGE_LABEL}_${UBUNTU_RELEASE}_root.img"
ROOT_SPARSE="${ROOT_IMG%.img}_sparse.img"

# Clean any leftover mounts
for d in run sys proc dev/pts dev; do
    if mountpoint -q "$ROOTFS_DIR/$d"; then
        sudo umount -l "$ROOTFS_DIR/$d"
    fi
done

# -------------------------------------------------------
# Step 1: UUID
# -------------------------------------------------------
BUILD_UUID=$(uuidgen)
echo ">>> UUID: $BUILD_UUID"
sed -i '/^ROOTFS_UUID=/d' build.env 2>/dev/null || true
echo "ROOTFS_UUID=$BUILD_UUID" >> build.env

# -------------------------------------------------------
# Step 2: DTB selection
# -------------------------------------------------------
# If BOOT_PANEL_PICKER is true, ask user. Otherwise use BOOT_DTB directly.
if [ "$BOOT_PANEL_PICKER" = "true" ]; then
    echo ""
    echo "Select display panel:"
    echo "1) Tianma (default)"
    echo "2) EBBG"
    read -p "Choice [1-2, default 1]: " PANEL_CHOICE
    case ${PANEL_CHOICE:-1} in
        2) SELECTED_DTB="sdm845-xiaomi-beryllium-ebbg.dtb"  ;;
        *) SELECTED_DTB="sdm845-xiaomi-beryllium-tianma.dtb" ;;
    esac
else
    SELECTED_DTB="$BOOT_DTB"
fi
echo ">>> DTB: $SELECTED_DTB"

# Write DTB name for kernel hook
sudo bash -c "echo '${SELECTED_DTB}' > '${ROOTFS_DIR}/etc/kernel/boot_dtb'"

# -------------------------------------------------------
# Step 3: Boot verbosity
# -------------------------------------------------------
echo ""
echo "Boot verbosity:"
echo "1) Quiet / splash (default)"
echo "2) Verbose"
read -p "Choice [1-2, default 1]: " BOOT_V
case ${BOOT_V:-1} in
    2) BOOT_EXTRA="" ;;
    *) BOOT_EXTRA="quiet splash" ;;
esac

# -------------------------------------------------------
# Step 4: Write /etc/kernel/cmdline + fstab
# -------------------------------------------------------
CMDLINE="root=UUID=${BUILD_UUID} rw rootwait console=tty0 console=ttyMSM0,115200n8 earlycon=qcom_geni,0x00A90000 ${BOOT_EXTRA}"

echo ">>> Writing /etc/kernel/cmdline..."
sudo bash -c "echo '${CMDLINE}' > '${ROOTFS_DIR}/etc/kernel/cmdline'"

echo ">>> Writing fstab..."
sudo bash -c "printf '# Mobuntu Orange — generated by 5_seal_rootfs.sh\nUUID=${BUILD_UUID}  /  ext4  errors=remount-ro  0  1\n' > '${ROOTFS_DIR}/etc/fstab'"

# -------------------------------------------------------
# Step 5: Boot image — method-specific
# -------------------------------------------------------
case "$BOOT_METHOD" in
mkbootimg)
    echo ">>> Finding boot assets..."
    KERNEL=$(ls -1tr "$ROOTFS_DIR"/boot/vmlinuz-*sdm845* 2>/dev/null | tail -n 1)
    INITRD=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img-*sdm845* 2>/dev/null | tail -n 1)
    DTB=$(find "$ROOTFS_DIR/usr/lib" "$ROOTFS_DIR/boot" \
        -type f -name "$SELECTED_DTB" 2>/dev/null | head -n 1)

    if [[ -z "$KERNEL" || -z "$INITRD" || -z "$DTB" ]]; then
        echo "ERROR: Missing boot assets."
        echo "  Kernel: ${KERNEL:-NOT FOUND}"
        echo "  Initrd: ${INITRD:-NOT FOUND}"
        echo "  DTB:    ${DTB:-NOT FOUND}"
        ls -la "$ROOTFS_DIR/boot/" 2>/dev/null || true
        exit 1
    fi

    echo ">>> Kernel: $(basename $KERNEL)"
    echo ">>> Initrd: $(basename $INITRD)"
    echo ">>> DTB:    $(basename $DTB)"

    if [ "$BOOT_DTB_APPEND" = "true" ]; then
        echo ">>> Appending DTB to kernel (required for this device)..."
        KERNEL_DTB=$(mktemp /tmp/kernel-dtb-XXXX)
        cat "$KERNEL" "$DTB" > "$KERNEL_DTB"
    else
        KERNEL_DTB="$KERNEL"
    fi

    echo ">>> Building boot.img..."
    mkbootimg \
        --kernel "$KERNEL_DTB" \
        --ramdisk "$INITRD" \
        --pagesize "$MKBOOTIMG_PAGESIZE" \
        --base "$MKBOOTIMG_BASE" \
        --kernel_offset "$MKBOOTIMG_KERNEL_OFFSET" \
        --ramdisk_offset "$MKBOOTIMG_RAMDISK_OFFSET" \
        --tags_offset "$MKBOOTIMG_TAGS_OFFSET" \
        --cmdline "$CMDLINE" \
        -o "$BOOT_IMG"

    [ "$BOOT_DTB_APPEND" = "true" ] && rm -f "$KERNEL_DTB"
    echo ">>> boot.img: $(du -h $BOOT_IMG | cut -f1)"
    ;;

uboot)
    echo ">>> U-Boot method: placeholder."
    echo ">>> UBOOT_URL=${UBOOT_URL}"
    echo ">>> Implement U-Boot packaging here when URL is defined."
    BOOT_IMG=""
    ;;

uefi)
    echo ">>> UEFI method: placeholder."
    echo ">>> UEFI_URL=${UEFI_URL}"
    echo ">>> Implement UEFI ESP packaging here when URL is defined."
    BOOT_IMG=""
    ;;

*)
    echo ">>> ERROR: Unknown BOOT_METHOD '$BOOT_METHOD'"
    exit 1
    ;;
esac

# -------------------------------------------------------
# Step 6: RootFS image
# -------------------------------------------------------
IMG_MB=$((IMAGE_SIZE * 1024))
echo ">>> Allocating ${IMAGE_SIZE}GB rootfs image..."
rm -f "$ROOT_IMG"
fallocate -l "${IMG_MB}M" "$ROOT_IMG"
mkfs.ext4 -U "$BUILD_UUID" -L "$DEVICE_IMAGE_LABEL" "$ROOT_IMG"

echo ">>> Rsyncing rootfs (this will take a while)..."
LOOP_MNT=$(mktemp -d /tmp/rootfs_mnt_XXXX)
sudo mount -o loop "$ROOT_IMG" "$LOOP_MNT"
sudo rsync -aHAXx \
    --exclude='/proc/*' --exclude='/sys/*' \
    --exclude='/dev/*'  --exclude='/run/*' \
    --exclude='/tmp/*' \
    "$ROOTFS_DIR/" "$LOOP_MNT/"
sudo sync
sudo umount "$LOOP_MNT"
rmdir "$LOOP_MNT"
echo ">>> RootFS: $(du -h $ROOT_IMG | cut -f1)"

# -------------------------------------------------------
# Step 7: Sparse conversion
# -------------------------------------------------------
if command -v img2simg &>/dev/null; then
    echo ">>> Converting to sparse..."
    img2simg "$ROOT_IMG" "$ROOT_SPARSE"
    FLASH_ROOT="$ROOT_SPARSE"
else
    echo ">>> img2simg not found, using raw image."
    FLASH_ROOT="$ROOT_IMG"
fi

# -------------------------------------------------------
# Flash instructions
# -------------------------------------------------------
echo ""
echo "======================================================="
echo "   DONE — $DEVICE_NAME"
echo "======================================================="
echo ""
if [ -n "$BOOT_IMG" ]; then
    echo "  fastboot flash boot   $(pwd)/$BOOT_IMG"
fi
echo "  fastboot flash system $(pwd)/$FLASH_ROOT"
echo "  fastboot reboot"
echo ""
case "$FIRMWARE_METHOD" in
git)
    echo "  Firmware was pre-staged from:"
    echo "  $FIRMWARE_REPO"
    echo "  No first-boot firmware step required."
    ;;
droid-juicer)
    echo "  IMPORTANT: droid-juicer will extract firmware"
    echo "  from vendor partition on first boot."
    echo "  Reboot a second time after first boot."
    ;;
apt)
    echo "  Firmware: shipped via linux-firmware apt package."
    ;;
esac
echo "======================================================="