#!/bin/bash
set -e
source build.env
echo "======================================================="
echo "   Mobuntu Orange ${UBUNTU_CODENAME} - [6/7] Seal & Package"
echo "   Device  : ${DEVICE_NAME} (${DEVICE_CODENAME})"
echo "   RootFS  : ${ROOTFS_DIR}"
echo "======================================================="

BOOT_IMG="mobuntu_${DEVICE_CODENAME}_${UBUNTU_CODENAME}_boot.img"
ROOT_IMG="mobuntu_${DEVICE_CODENAME}_${UBUNTU_CODENAME}_root.img"
ROOT_SPARSE="${ROOT_IMG%.img}_sparse.img"

# Ensure clean mounts before packing
for d in run sys proc dev/pts dev; do
    if mountpoint -q "$ROOTFS_DIR/$d"; then
        sudo umount -l "$ROOTFS_DIR/$d"
    fi
done

# -----------------------------------------
# Step 1: UUID Generation & Environment Sync
# -----------------------------------------
BUILD_UUID=$(uuidgen)
echo ">>> Generated Master UUID: $BUILD_UUID"
sed -i '/^ROOTFS_UUID=/d' build.env 2>/dev/null || true
echo "ROOTFS_UUID=$BUILD_UUID" >> build.env

# -----------------------------------------
# Step 2: Harvest Boot Assets
# -----------------------------------------
echo ">>> Hunting for kernel assets in $ROOTFS_DIR/boot/..."

KERNEL=$(ls -1tr "$ROOTFS_DIR"/boot/vmlinuz* "$ROOTFS_DIR"/boot/Image* 2>/dev/null | grep -v dtb | tail -n 1)
INITRD=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img* "$ROOTFS_DIR"/boot/initramfs* 2>/dev/null | tail -n 1)

echo ""
echo "Select your ${DEVICE_NAME} display panel variant:"
echo "1) Tianma  (most common, default)"
echo "2) EBBG"
read -p "Choice [1-2, default 1]: " PANEL_CHOICE
PANEL_CHOICE=${PANEL_CHOICE:-1}
case $PANEL_CHOICE in
    2) DTB_NAME="sdm845-xiaomi-beryllium-ebbg.dtb"  ; PANEL_NAME="EBBG"   ;;
    *) DTB_NAME="sdm845-xiaomi-beryllium-tianma.dtb" ; PANEL_NAME="Tianma" ;;
esac
echo ">>> Using panel: $PANEL_NAME ($DTB_NAME)"

DTB=$(find "$ROOTFS_DIR/usr/lib" "$ROOTFS_DIR/boot" \
    -type f -name "$DTB_NAME" 2>/dev/null | head -n 1)

if [[ -z "$KERNEL" || -z "$INITRD" || -z "$DTB" ]]; then
    echo "ERROR: Missing boot assets. Contents of ${ROOTFS_DIR}/boot/:"
    ls -la "$ROOTFS_DIR/boot/" 2>/dev/null || echo "(directory empty or missing)"
    if [ -z "$DTB" ]; then
        echo "Available DTBs:"
        find "$ROOTFS_DIR/usr/lib" "$ROOTFS_DIR/boot" -name "*beryllium*.dtb" 2>/dev/null || true
    fi
    exit 1
fi

echo ">>> Harvested Assets:"
echo "    Kernel: $(basename "$KERNEL")"
echo "    Initrd: $(basename "$INITRD")"
echo "    DTB:    $DTB"

# SDM845 requires DTB appended directly to the kernel binary
echo ">>> Appending DTB to kernel (required for SDM845 bootloader)..."
KERNEL_DTB=$(mktemp /tmp/kernel-dtb-XXXX)
cat "$KERNEL" "$DTB" > "$KERNEL_DTB"
echo ">>> kernel+dtb size: $(du -h "$KERNEL_DTB" | cut -f1)"

# -----------------------------------------
# Boot Verbosity Picker
# -----------------------------------------
echo ""
echo "Select boot verbosity:"
echo "1) Quiet (splash screen, default)"
echo "2) Verbose (full kernel log on boot)"
read -p "Choice [1-2, default 1]: " BOOT_VERBOSE
BOOT_VERBOSE=${BOOT_VERBOSE:-1}
case $BOOT_VERBOSE in
    2) BOOT_CMDLINE_EXTRA="" ;;
    *) BOOT_CMDLINE_EXTRA="quiet splash" ;;
esac

# -----------------------------------------
# Step 3: Fstab Injection
# -----------------------------------------
FSTAB_FILE="$ROOTFS_DIR/etc/fstab"
sudo bash -c "cat > $FSTAB_FILE" << FSTAB
# Generated by Mobuntu Orange ${UBUNTU_CODENAME} build toolkit
UUID=$BUILD_UUID / ext4 errors=remount-ro 0 1
FSTAB
echo ">>> fstab written with UUID $BUILD_UUID"

# -----------------------------------------
# Step 4: Forge boot.img
# -----------------------------------------
echo ">>> Packing boot.img..."
mkbootimg \
  --kernel "$KERNEL_DTB" \
  --ramdisk "$INITRD" \
  --pagesize 4096 \
  --base 0x00000000 \
  --kernel_offset 0x00008000 \
  --ramdisk_offset 0x01000000 \
  --tags_offset 0x00000100 \
  --cmdline "root=UUID=${BUILD_UUID} rw rootwait console=tty0 console=ttyMSM0,115200n8 earlycon=qcom_geni,0x00A90000 PMOS_NOSPLASH $BOOT_CMDLINE_EXTRA" \
  -o "$BOOT_IMG"

rm -f "$KERNEL_DTB"
echo ">>> boot.img packed: $(du -h "$BOOT_IMG" | cut -f1)"

# -----------------------------------------
# Step 5: Burn RootFS via loop device + rsync
# -----------------------------------------
IMG_MB=$((IMAGE_SIZE * 1024))
echo ">>> Allocating ${IMAGE_SIZE}GB raw image..."
rm -f "$ROOT_IMG"
fallocate -l "${IMG_MB}M" "$ROOT_IMG"

echo ">>> Formatting as ext4 with UUID $BUILD_UUID..."
mkfs.ext4 -U "$BUILD_UUID" -L "mobuntu-${DEVICE_CODENAME}" "$ROOT_IMG"

echo ">>> Mounting image and rsyncing rootfs (this will take a while)..."
LOOP_MNT=$(mktemp -d /tmp/rootfs_mnt_XXXX)
sudo mount -o loop "$ROOT_IMG" "$LOOP_MNT"

sudo rsync -aHAXx \
    --exclude='/proc/*' \
    --exclude='/sys/*' \
    --exclude='/dev/*' \
    --exclude='/run/*' \
    --exclude='/tmp/*' \
    "$ROOTFS_DIR/" "$LOOP_MNT/"

echo ">>> Syncing and unmounting..."
sudo sync
sudo umount "$LOOP_MNT"
rmdir "$LOOP_MNT"
echo ">>> RootFS image written: $(du -h "$ROOT_IMG" | cut -f1)"

# -----------------------------------------
# Step 6: Convert to sparse for fastboot
# -----------------------------------------
if ! command -v img2simg &>/dev/null; then
    sudo apt-get install -y android-sdk-libsparse-utils 2>/dev/null || true
fi

echo ""
if command -v img2simg &>/dev/null; then
    echo ">>> Converting to sparse image..."
    img2simg "$ROOT_IMG" "$ROOT_SPARSE"
    echo "======================================================="
    echo "   Mobuntu Orange ${UBUNTU_CODENAME} - ${DEVICE_NAME}"
    echo "   FLASHING INSTRUCTIONS"
    echo "======================================================="
    echo ">>> Boot device into fastboot mode (Vol Down + Power)"
    echo ">>> Then run:"
    echo ""
    echo "   fastboot flash boot    $(pwd)/$BOOT_IMG"
    echo "   fastboot flash -S 100M userdata  $(pwd)/$ROOT_SPARSE"
    echo "   fastboot reboot"
    echo ""
    echo ">>> NOTE: On first boot droid-juicer will extract signed"
    echo ">>> firmware from your Android vendor partition, then reboot."
    echo "======================================================="
else
    echo ">>> WARNING: img2simg not found, using raw image."
    echo "======================================================="
    echo "   Mobuntu Orange ${UBUNTU_CODENAME} - ${DEVICE_NAME}"
    echo "   FLASHING INSTRUCTIONS"
    echo "======================================================="
    echo ">>> Boot device into fastboot mode (Vol Down + Power)"
    echo ">>> Then run:"
    echo ""
    echo "   fastboot flash boot    $(pwd)/$BOOT_IMG"
    echo "   fastboot flash -S 100M userdata  $(pwd)/$ROOT_IMG"
    echo "   fastboot reboot"
    echo "======================================================="
fi
