#!/bin/bash
set -e
source build.env

echo "======================================================="
echo "   Mobuntu Orange — [5/5] Seal & Flash"
echo "======================================================="

BOOT_IMG="mobuntu_beryllium_${UBUNTU_RELEASE}_boot.img"
ROOT_IMG="mobuntu_beryllium_${UBUNTU_RELEASE}_root.img"
ROOT_SPARSE="${ROOT_IMG%.img}_sparse.img"

# Ensure no leftover mounts
for d in run sys proc dev/pts dev; do
    if mountpoint -q "$ROOTFS_DIR/$d"; then
        sudo umount -l "$ROOTFS_DIR/$d"
    fi
done

# -------------------------------------------------------
# Step 1: Generate UUID
# -------------------------------------------------------
BUILD_UUID=$(uuidgen)
echo ">>> Generated UUID: $BUILD_UUID"
sed -i '/^ROOTFS_UUID=/d' build.env 2>/dev/null || true
echo "ROOTFS_UUID=$BUILD_UUID" >> build.env

# -------------------------------------------------------
# Step 2: Panel picker
# -------------------------------------------------------
echo ""
echo "Select your Poco F1 display panel:"
echo "1) Tianma (most common, default)"
echo "2) EBBG"
read -p "Choice [1-2, default 1]: " PANEL_CHOICE
PANEL_CHOICE=${PANEL_CHOICE:-1}
case $PANEL_CHOICE in
    2) DTB_NAME="sdm845-xiaomi-beryllium-ebbg.dtb";  PANEL_NAME="EBBG"   ;;
    *) DTB_NAME="sdm845-xiaomi-beryllium-tianma.dtb"; PANEL_NAME="Tianma" ;;
esac
echo ">>> Panel: $PANEL_NAME"

# -------------------------------------------------------
# Step 3: Boot verbosity picker
# -------------------------------------------------------
echo ""
echo "Boot verbosity:"
echo "1) Quiet / splash (default)"
echo "2) Verbose (full kernel log)"
read -p "Choice [1-2, default 1]: " BOOT_V
BOOT_V=${BOOT_V:-1}
case $BOOT_V in
    2) BOOT_EXTRA="" ;;
    *) BOOT_EXTRA="quiet splash" ;;
esac

# -------------------------------------------------------
# Step 4: Write /etc/kernel/cmdline (used by kernel hook)
# -------------------------------------------------------
CMDLINE="root=UUID=${BUILD_UUID} rw rootwait console=tty0 console=ttyMSM0,115200n8 earlycon=qcom_geni,0x00A90000 ${BOOT_EXTRA}"
echo ">>> Writing /etc/kernel/cmdline..."
sudo bash -c "echo '${CMDLINE}' > '${ROOTFS_DIR}/etc/kernel/cmdline'"

# -------------------------------------------------------
# Step 5: Write fstab
# -------------------------------------------------------
echo ">>> Writing fstab..."
sudo bash -c "cat > '${ROOTFS_DIR}/etc/fstab'" << FSTAB_EOF
# Mobuntu Orange — generated by 5_seal_rootfs.sh
UUID=${BUILD_UUID}  /          ext4   errors=remount-ro  0  1
UUID=EEFB-EEFB      /boot/efi  vfat   umask=0077         0  1
FSTAB_EOF

# -------------------------------------------------------
# Step 6: Harvest boot assets
# -------------------------------------------------------
echo ">>> Finding boot assets..."

KERNEL=$(ls -1tr "$ROOTFS_DIR"/boot/vmlinuz-* "$ROOTFS_DIR"/boot/Image* 2>/dev/null \
    | grep -v '\.dtb$' | tail -n 1)
INITRD=$(ls -1tr "$ROOTFS_DIR"/boot/initrd.img-* "$ROOTFS_DIR"/boot/initramfs-* 2>/dev/null \
    | tail -n 1)
DTB=$(find "$ROOTFS_DIR/usr/lib" "$ROOTFS_DIR/boot" \
    -type f -name "$DTB_NAME" 2>/dev/null | head -n 1)

if [[ -z "$KERNEL" || -z "$INITRD" || -z "$DTB" ]]; then
    echo "ERROR: Missing boot assets."
    echo "  Kernel: ${KERNEL:-NOT FOUND}"
    echo "  Initrd: ${INITRD:-NOT FOUND}"
    echo "  DTB:    ${DTB:-NOT FOUND}"
    ls -la "$ROOTFS_DIR/boot/" 2>/dev/null || true
    exit 1
fi

echo ">>> Assets:"
echo "    Kernel: $(basename "$KERNEL")"
echo "    Initrd: $(basename "$INITRD")"
echo "    DTB:    $(basename "$DTB")"

# -------------------------------------------------------
# Step 7: Build boot.img
# -------------------------------------------------------
echo ">>> Appending DTB to kernel (required for SDM845)..."
KERNEL_DTB=$(mktemp /tmp/kernel-dtb-XXXX)
cat "$KERNEL" "$DTB" > "$KERNEL_DTB"

echo ">>> Building boot.img..."
mkbootimg \
    --kernel "$KERNEL_DTB" \
    --ramdisk "$INITRD" \
    --pagesize 4096 \
    --base 0x00000000 \
    --kernel_offset 0x00008000 \
    --ramdisk_offset 0x01000000 \
    --tags_offset 0x00000100 \
    --cmdline "$CMDLINE" \
    -o "$BOOT_IMG"

rm -f "$KERNEL_DTB"
echo ">>> boot.img built: $(du -h "$BOOT_IMG" | cut -f1)"

# -------------------------------------------------------
# Step 8: Build rootfs image
# -------------------------------------------------------
IMG_MB=$((IMAGE_SIZE * 1024))
echo ">>> Allocating ${IMAGE_SIZE}GB rootfs image..."
rm -f "$ROOT_IMG"
fallocate -l "${IMG_MB}M" "$ROOT_IMG"

echo ">>> Formatting ext4 (UUID: $BUILD_UUID)..."
mkfs.ext4 -U "$BUILD_UUID" -L "mobuntu-beryllium" "$ROOT_IMG"

echo ">>> Mounting and rsyncing rootfs (this will take a while)..."
LOOP_MNT=$(mktemp -d /tmp/rootfs_mnt_XXXX)
sudo mount -o loop "$ROOT_IMG" "$LOOP_MNT"

sudo rsync -aHAXx \
    --exclude='/proc/*' \
    --exclude='/sys/*' \
    --exclude='/dev/*' \
    --exclude='/run/*' \
    --exclude='/tmp/*' \
    "$ROOTFS_DIR/" "$LOOP_MNT/"

sudo sync
sudo umount "$LOOP_MNT"
rmdir "$LOOP_MNT"
echo ">>> RootFS image: $(du -h "$ROOT_IMG" | cut -f1)"

# -------------------------------------------------------
# Step 9: Sparse conversion
# -------------------------------------------------------
if command -v img2simg &>/dev/null; then
    echo ">>> Converting to sparse image for fastboot..."
    img2simg "$ROOT_IMG" "$ROOT_SPARSE"
    FLASH_ROOT="$ROOT_SPARSE"
else
    echo ">>> WARNING: img2simg not found, using raw image."
    FLASH_ROOT="$ROOT_IMG"
fi

# -------------------------------------------------------
# Flash instructions
# -------------------------------------------------------
echo ""
echo "======================================================="
echo "   DONE — Flash Instructions"
echo "======================================================="
echo ""
echo "  Boot your Poco F1 into fastboot mode, then run:"
echo ""
echo "    fastboot flash boot   $(pwd)/$BOOT_IMG"
echo "    fastboot flash system $(pwd)/$FLASH_ROOT"
echo "    fastboot reboot"
echo ""
echo "  IMPORTANT — First boot:"
echo "    droid-juicer will extract firmware from your"
echo "    vendor partition automatically on first boot."
echo "    WiFi, modem, and DSP will be unavailable until"
echo "    this completes and you reboot a second time."
echo ""
echo "  Subsequent OTA kernel updates:"
echo "    apt upgrade will automatically rebuild boot.img"
echo "    via /etc/kernel/postinst.d/zz-qcom-bootimg."
echo "    Use qbootctl to update the boot slot without fastboot."
echo "======================================================="
